### ISSUE TITLE
Facegen Instructions Issue

### ISSUE THREAD

**Issue by ghost** [caiobraz/sr.kaio-seasoning#13]
Hi there! Thnx a bunch for everything :) I'll (try to) keep it short and to the point.

- Under "6 - Finishing Up" you've left instructions to go to TPF's Facegen page. However, the link you provide is broken and it appears TPF-site no longer provides instructions for regenerating facegen anywhere on its site. (Too bad).

- In your setup instructions for generating facegen files you state that "NPCsWithFaces.esp" should be the active file in the Creation Kit. However, I have no such .esp in my load order and I cannot find it anywhere among the files I've been instructed to download. I've tried googling it, but no luck. Where does this file come from? 

And without it, what _do_ I set as the active file? (I still cannot figure out how to generate facegen files. The logic of which files to include in the generative process and which to set as the active file completely eludes me. Noob remains noobish on this point.

Bye bye!

**Comment by caiobraz** [comment]
Hello!

Thanks for the input! The guide is currently outdated indeed, I did miss the 4.6 update from TPF, and now I'm working on a update for 4.7.2, should be up tomorrow :)

Thanks again!

**Comment by ghost** [comment]
I have no idea if this will reach you, but thnx for the updates! Also: I took a look at your profile picture on Github. Dude, we look so much alike we could be brothers, haha!

Van: Caio Braz ***@***.***>
Verzonden: donderdag 19 augustus 2021 19:36
Aan: caiobraz/sr.kaio-seasoning ***@***.***>
CC: Synec82 ***@***.***>; Author ***@***.***>
Onderwerp: Re: [caiobraz/sr.kaio-seasoning] Facegen Instructions Issue (#13)


Closed #13<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcaiobraz%2Fsr.kaio-seasoning%2Fissues%2F13&data=04%7C01%7C%7C4004d7661ad34cc6b71208d96337d7c3%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637649913765754234%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=C2VDezlMmhawxgrpSZgL4tXwiUTwxWsSaY2oIJGoXoE%3D&reserved=0>.

-
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcaiobraz%2Fsr.kaio-seasoning%2Fissues%2F13%23event-5182672217&data=04%7C01%7C%7C4004d7661ad34cc6b71208d96337d7c3%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637649913765764189%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=BT27muG4%2F65Ss%2FJLL9W6A2X%2Bzr8rfoNpoRQp5%2FW7Nl8%3D&reserved=0>, or unsubscribe<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAVIEOIQ4LCJUMWFUXRRTJLLT5U6I3ANCNFSM5CMHLSKA&data=04%7C01%7C%7C4004d7661ad34cc6b71208d96337d7c3%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637649913765764189%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=hW4OjXRR7G5CLi5QvpUJp6gxAOx3LAE4jQv65PJTqqQ%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7C4004d7661ad34cc6b71208d96337d7c3%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637649913765774148%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=rj0AWAwViEH60R87REs1PPRU4VS3lO2sun0wLm%2BychE%3D&reserved=0> or Android<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26utm_campaign%3Dnotification-email&data=04%7C01%7C%7C4004d7661ad34cc6b71208d96337d7c3%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637649913765774148%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=DgGSr49%2FUPDqku6wfL%2Fb6QkIlFDAsHvK6Ucf7ofh5sY%3D&reserved=0>.
